#############################################################################
# Makefile for building: ../../out/bin/E4MT
# Generated by qmake (3.0) (Qt 5.6.2)
# Project:  E4MT.pro
# Template: app
# Command: /usr/bin/qmake-qt5 CONFIG+=debug CONFIG+=WITH_QJsonRPC -o Makefile E4MT.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DTARGOMAN_SHOW_DEBUG=1 -DTARGOMAN_DEBUG_PROCESS_LINE=1 -DTARGOMAN_SHOW_WARNING=1 -DTARGOMAN_SHOW_INFO=1 -DTARGOMAN_SHOW_HAPPY=1 -DTARGOMAN_SHOW_NORMAL=1 -DPROJ_VERSION=1.0.0 -DWITH_QJsonRPC -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -g -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/libxml2 -I../../out/include -I../../out/include -I/home/user/local/include -I/ -I../../out/include -I./libsrc -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -I../../out/build/E4MT/moc -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = E4MT1.0.0
DISTDIR = /home/user/SVN/Targoman/targoman/New\ Structure/TextProcessor/out/build/E4MT/obj/E4MT1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -L./../../out/./lib -L/home/user/local/lib -lTargomanCommon -lTargomanTextProcessor -lxml2 -lQJsonRPC -lQt5Core -L/usr/lib64 -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ../../out/build/E4MT/obj/

####### Files

SOURCES       = src/main.cpp \
		src/appE4MT.cpp \
		src/Configs.cpp \
		src/XMLReader.cpp ../../out/build/E4MT/moc/moc_appE4MT.cpp
OBJECTS       = ../../out/build/E4MT/obj/main.o \
		../../out/build/E4MT/obj/appE4MT.o \
		../../out/build/E4MT/obj/Configs.o \
		../../out/build/E4MT/obj/XMLReader.o \
		../../out/build/E4MT/obj/moc_appE4MT.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		../../Project.pri \
		Configs.pri \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		E4MT.pro src/appE4MT.h \
		src/Configs.h \
		src/XMLReader.h src/main.cpp \
		src/appE4MT.cpp \
		src/Configs.cpp \
		src/XMLReader.cpp
QMAKE_TARGET  = E4MT
DESTDIR       = ../../out/bin/
TARGET        = ../../out/bin/E4MT


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d ../../out/bin/ || mkdir -p ../../out/bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: E4MT.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		../../Project.pri \
		Configs.pri \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		E4MT.pro \
		/home/user/local/lib/libTargomanCommon.prl \
		../../out/lib/libTargomanTextProcessor.prl \
		/home/user/local/lib/libQJsonRPC.prl \
		/usr/lib64/libQt5Core.prl
	$(QMAKE) CONFIG+=debug CONFIG+=WITH_QJsonRPC -o Makefile E4MT.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_AkonadiMime.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
../../Project.pri:
Configs.pri:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
E4MT.pro:
/home/user/local/lib/libTargomanCommon.prl:
../../out/lib/libTargomanTextProcessor.prl:
/home/user/local/lib/libQJsonRPC.prl:
/usr/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) CONFIG+=debug CONFIG+=WITH_QJsonRPC -o Makefile E4MT.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/appE4MT.h src/Configs.h src/XMLReader.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/appE4MT.cpp src/Configs.cpp src/XMLReader.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: ../../out/build/E4MT/moc/moc_appE4MT.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) ../../out/build/E4MT/moc/moc_appE4MT.cpp
../../out/build/E4MT/moc/moc_appE4MT.cpp: /home/user/local/include/libTargomanCommon/clsSafeCoreApplication.h \
		/home/user/local/include/libTargomanCommon/CmdIO.h \
		/home/user/local/include/libTargomanCommon/Macros.h \
		/home/user/local/include/libTargomanCommon/Configuration/intfRPCExporter.hpp \
		/home/user/local/include/libTargomanCommon/Types.h \
		/home/user/local/include/libTargomanCommon/JSONConversationProtocol.h \
		/home/user/local/include/libTargomanCommon/exTargomanBase.h \
		src/appE4MT.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I'/home/user/SVN/Targoman/targoman/New Structure/TextProcessor/Apps/E4MT' -I/usr/include/libxml2 -I'/home/user/SVN/Targoman/targoman/New Structure/TextProcessor/out/include' -I'/home/user/SVN/Targoman/targoman/New Structure/TextProcessor/out/include' -I/home/user/local/include -I/ -I'/home/user/SVN/Targoman/targoman/New Structure/TextProcessor/out/include' -I'/home/user/SVN/Targoman/targoman/New Structure/TextProcessor/Apps/E4MT/libsrc' -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I/usr/include/c++/4.8 -I/usr/include/c++/4.8/x86_64-suse-linux -I/usr/include/c++/4.8/backward -I/usr/lib64/gcc/x86_64-suse-linux/4.8/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/4.8/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include src/appE4MT.h -o ../../out/build/E4MT/moc/moc_appE4MT.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

../../out/build/E4MT/obj/main.o: src/main.cpp /home/user/local/include/libTargomanCommon/Macros.h \
		/home/user/local/include/libTargomanCommon/Configuration/ConfigManager.h \
		/home/user/local/include/libTargomanCommon/exTargomanBase.h \
		/home/user/local/include/libTargomanCommon/CmdIO.h \
		/home/user/local/include/libTargomanCommon/Configuration/intfConfigurable.hpp \
		/home/user/local/include/libTargomanCommon/Configuration/intfConfigurableModule.hpp \
		/home/user/local/include/libTargomanCommon/Logger.h \
		/home/user/local/include/libTargomanCommon/Helpers.hpp \
		/home/user/local/include/libTargomanCommon/Types.h \
		/home/user/local/include/libQJsonRPC/qjsonrpcservice.h \
		/home/user/local/include/libQJsonRPC/qjsonrpcmessage.h \
		/home/user/local/include/libQJsonRPC/qjsonrpcglobal.h \
		src/appE4MT.h \
		/home/user/local/include/libTargomanCommon/clsSafeCoreApplication.h \
		/home/user/local/include/libTargomanCommon/Configuration/intfRPCExporter.hpp \
		/home/user/local/include/libTargomanCommon/JSONConversationProtocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../out/build/E4MT/obj/main.o src/main.cpp

../../out/build/E4MT/obj/appE4MT.o: src/appE4MT.cpp src/appE4MT.h \
		/home/user/local/include/libTargomanCommon/clsSafeCoreApplication.h \
		/home/user/local/include/libTargomanCommon/CmdIO.h \
		/home/user/local/include/libTargomanCommon/Macros.h \
		/home/user/local/include/libTargomanCommon/Configuration/intfRPCExporter.hpp \
		/home/user/local/include/libTargomanCommon/Types.h \
		/home/user/local/include/libTargomanCommon/JSONConversationProtocol.h \
		/home/user/local/include/libTargomanCommon/exTargomanBase.h \
		../../out/include/libTargomanTextProcessor/TextProcessor.h \
		/home/user/local/include/libTargomanCommon/Logger.h \
		/home/user/local/include/ISO639.h \
		src/XMLReader.h \
		src/Configs.h \
		/home/user/local/include/libTargomanCommon/Configuration/tmplConfigurable.h \
		/home/user/local/include/libTargomanCommon/Configuration/intfConfigurable.hpp \
		/home/user/local/include/libTargomanCommon/Configuration/ConfigManager.h \
		/home/user/local/include/libTargomanCommon/Configuration/intfConfigurableModule.hpp \
		/home/user/local/include/libTargomanCommon/Helpers.hpp \
		/home/user/local/include/libQJsonRPC/qjsonrpcservice.h \
		/home/user/local/include/libQJsonRPC/qjsonrpcmessage.h \
		/home/user/local/include/libQJsonRPC/qjsonrpcglobal.h \
		/home/user/local/include/libTargomanCommon/FastOperations.hpp \
		/home/user/local/include/libTargomanCommon/Configuration/Validators.hpp \
		/home/user/local/include/libTargomanCommon/Constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../out/build/E4MT/obj/appE4MT.o src/appE4MT.cpp

../../out/build/E4MT/obj/Configs.o: src/Configs.cpp src/Configs.h \
		/home/user/local/include/libTargomanCommon/Configuration/tmplConfigurable.h \
		/home/user/local/include/libTargomanCommon/Configuration/intfConfigurable.hpp \
		/home/user/local/include/libTargomanCommon/Macros.h \
		/home/user/local/include/libTargomanCommon/Configuration/ConfigManager.h \
		/home/user/local/include/libTargomanCommon/exTargomanBase.h \
		/home/user/local/include/libTargomanCommon/CmdIO.h \
		/home/user/local/include/libTargomanCommon/Configuration/intfConfigurableModule.hpp \
		/home/user/local/include/libTargomanCommon/Logger.h \
		/home/user/local/include/libTargomanCommon/Helpers.hpp \
		/home/user/local/include/libTargomanCommon/Types.h \
		/home/user/local/include/libQJsonRPC/qjsonrpcservice.h \
		/home/user/local/include/libQJsonRPC/qjsonrpcmessage.h \
		/home/user/local/include/libQJsonRPC/qjsonrpcglobal.h \
		/home/user/local/include/libTargomanCommon/FastOperations.hpp \
		/home/user/local/include/libTargomanCommon/Configuration/Validators.hpp \
		/home/user/local/include/libTargomanCommon/Constants.h \
		/home/user/local/include/ISO639.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../out/build/E4MT/obj/Configs.o src/Configs.cpp

../../out/build/E4MT/obj/XMLReader.o: src/XMLReader.cpp src/XMLReader.h \
		src/Configs.h \
		/home/user/local/include/libTargomanCommon/Configuration/tmplConfigurable.h \
		/home/user/local/include/libTargomanCommon/Configuration/intfConfigurable.hpp \
		/home/user/local/include/libTargomanCommon/Macros.h \
		/home/user/local/include/libTargomanCommon/Configuration/ConfigManager.h \
		/home/user/local/include/libTargomanCommon/exTargomanBase.h \
		/home/user/local/include/libTargomanCommon/CmdIO.h \
		/home/user/local/include/libTargomanCommon/Configuration/intfConfigurableModule.hpp \
		/home/user/local/include/libTargomanCommon/Logger.h \
		/home/user/local/include/libTargomanCommon/Helpers.hpp \
		/home/user/local/include/libTargomanCommon/Types.h \
		/home/user/local/include/libQJsonRPC/qjsonrpcservice.h \
		/home/user/local/include/libQJsonRPC/qjsonrpcmessage.h \
		/home/user/local/include/libQJsonRPC/qjsonrpcglobal.h \
		/home/user/local/include/libTargomanCommon/FastOperations.hpp \
		/home/user/local/include/libTargomanCommon/Configuration/Validators.hpp \
		/home/user/local/include/libTargomanCommon/Constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../out/build/E4MT/obj/XMLReader.o src/XMLReader.cpp

../../out/build/E4MT/obj/moc_appE4MT.o: ../../out/build/E4MT/moc/moc_appE4MT.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../out/build/E4MT/obj/moc_appE4MT.o ../../out/build/E4MT/moc/moc_appE4MT.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/user/local/ || mkdir -p $(INSTALL_ROOT)/home/user/local/
	rm -rvf /home/user/local/lib/lib/; mkdir -p /home/user/local/./include/; cp -Lr ./../../out/./include /home/user/local/./include/..;
	-$(INSTALL_DIR) /home/user/SVN/Targoman/targoman/New\ Structure/TextProcessor/out/bin $(INSTALL_ROOT)/home/user/local/
	-$(INSTALL_DIR) /home/user/SVN/Targoman/targoman/New\ Structure/TextProcessor/out/lib $(INSTALL_ROOT)/home/user/local/
	-$(INSTALL_DIR) /home/user/SVN/Targoman/targoman/New\ Structure/TextProcessor/out/conf $(INSTALL_ROOT)/home/user/local/

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/user/local/conf
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/user/local/lib
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/user/local/bin
	-$(DEL_DIR) $(INSTALL_ROOT)/home/user/local/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

